[WIP] Anatomy page
scilus/scil-documentation pull request #75
Opened 2024-01-12 19:09 UTC by EmmaRenauld

2024-01-17 16:58 UTC, ThoumyreStanislas commented on source/arriving/anatomy.rst
> +- AC:
AC : Anterior Commissure
FAT : Frontal Aslant Tract
FPT : Frontopontine Tract
ICP : Inferior Cerebellar Peduncle
IFOF : Inferior Fronto-Occipital Fasciculus
ILF : Inferior Longitudinal Fasciculus
MCP : Middle Cerebellar Peduncle
MdLF : Middle Longitudinal Fascicle
PC : Posterior Commissure
POPT : Parieto-Occipital Pontine Tract
PyT : Pyramidal Tract
SCP : Superior Cerebellar Peduncle
SLF : Superior Longitudinal Fasciculus
UF : Uncinate Fasciculus

2024-01-17 18:28 UTC, EmmaRenauld commented on source/arriving/anatomy.rst
> +- AC:
Thanks!

2024-01-17 19:12 UTC, EmmaRenauld commented
Here's what it looks like for the moment.

[Discover the brain anatomy — scil-documentation documentation.pdf](https://github.com/scilus/scil-documentation/files/13967592/Discover.the.brain.anatomy.scil-documentation.documentation.pdf)

@mdesco , I would have put more images from the links I point to, but I'm not sure that I can with the 'droit d'auteurs'. What to you think?

2024-05-22 17:43 UTC, CHrlS98 commented
@EmmaRenauld Should it go in the "Intro to" sections instead of "arriving"? We're think of renaming the intro sections to something like "Handbook/Quick reference guide of computer sciences" or maybe it could be "Handbook of neuroinformatics"?

2024-05-22 17:47 UTC, EmmaRenauld commented
Sure. When I created this, "intro to" were more Francois's stuff. But tell me where to put it and how to name it!

2024-05-22 18:36 UTC, karanphil commented
This is great! I would indeed move this to "Intro to" for the moment. We will move it later when we figure out what to do with that section.

2024-05-22 19:03 UTC, CHrlS98 requested changes
Based on the discussion --> Move to "intro to" section and keep same name for now !

2024-05-23 19:37 UTC, EmmaRenauld commented
When I made the change, it felt weird because the title of the section is "Intro to computer science":
![image](https://github.com/scilus/scil-documentation/assets/4967417/5be9412a-2dd6-407e-9959-58321e10797b)

And this is not. So I create a new section: "Intro to medical imaging". Maybe at some point we will have other things in there. Max's introduction to dMRI for instance?

2024-05-23 20:30 UTC, CHrlS98 approved these changes
All these "Intro to" pages could simply be under a "Quick reference" umbrella or something... but for now this is good enough for me.

2024-05-29 14:30 UTC, merged